package mybank;


import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kulsh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Connection con;
    Statement stmt;ResultSet rs;
    String query;
    Random rnd = new Random();
    
    //Worker Login
    void workerLogin() {
        try {
            query = "SELECT * FROM users WHERE user_id = "+id.getText()+" AND super_user = '"+name.getText()+"' AND user_password = '"+password.getText()+"' AND super_user IS NOT null";
            //System.out.println(query);
            rs = stmt.executeQuery(query);
            if(rs.next()) {
                
                //Go To Worker Panel
                WorkerPanel w = new WorkerPanel();
                w.user_id = id.getText();
                w.setVisible(true);
            }
            else {
                message.setText("Wrong ID or Name Or Password !"); 
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("Worker Login Error !");
        }
    }
    
    //User Login
void userLogin() {
        try {
            query = "SELECT * FROM users as u INNER JOIN accounts as a ON a.name = '"+name2.getText()+"' WHERE u.user_id = "+id2.getText()+" AND u.user_password = '"+password2.getText()+"';";
//            System.out.println(query);
            rs = stmt.executeQuery(query);
            if(rs.next()) {
                
                //Go To A/c User Panel
                UserPanel u = new UserPanel();
                u.user_id = id2.getText();
                u.setVisible(true); 
            }
            else {
                message2.setText("Wrong ID or Name Or Password !"); 
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("User Login Error !");
        }
    }
    
    //Create User
    void createUser() {
        try {
            query = "SELECT * FROM accounts where name = '"+name3.getText()+"' AND ac_no = '"+acNo.getText()+"' AND ac_id = "+id3.getText()+";";
//            System.out.println(query);
            rs = stmt.executeQuery(query);
            if(rs.next()) {
                query = "insert into users (user_id, ac_id, user_password) values ("+rnd.nextInt(500,2000)+", "+id3.getText()+", '"+password3.getText()+"')";
                if(stmt.executeUpdate(query)==1) {
                    query = "select * from users where ac_id ="+ id3.getText();
                    rs = stmt.executeQuery(query);
                    if(rs.next()) {
                        message3.setText("User Will Be Created ! Go to Login Page !"); 
                        message4.setText("Your User ID: "+ rs.getString("user_id")); 
                    }
                } else {
                    message3.setText("Some Error To Create User A/c!");
                }
            }
            else {
                message3.setText("Wrong A/c ID or Name Or A/c No !"); 
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            System.out.println("Create User Error !");
        }
    }
    
    public Home() {
        initComponents();
        
        //Set Full Screen Frame
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank?verifyServerCertificate=false&useSSL=true","root","");
            stmt = con.createStatement();
            
        }
        catch(Exception ex) {
            System.out.println("Error : "+ex.getMessage());
            System.out.println("Database Exception !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        login = new javax.swing.JButton();
        createUser = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        Heading2 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        workerLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        userPanel1 = new javax.swing.JPanel();
        Heading3 = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        userLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        id2 = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();
        CreateUser = new javax.swing.JPanel();
        acdetailsPanel = new javax.swing.JPanel();
        Heading4 = new javax.swing.JLabel();
        message3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        password3 = new javax.swing.JTextField();
        createUserbutton = new javax.swing.JButton();
        id4 = new javax.swing.JLabel();
        id3 = new javax.swing.JTextField();
        message4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(120, 120, 120));
        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainPanel.setPreferredSize(new java.awt.Dimension(730, 730));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        MainPanel.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 50));

        login.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        MainPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 160, 50));

        createUser.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        createUser.setText("Create User");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });
        MainPanel.add(createUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 160, 50));

        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        MainPanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 160, 50));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 51));

        Heading.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Heading.setText("Welcome To Onion Bank");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap(601, Short.MAX_VALUE)
                .addComponent(Heading)
                .addContainerGap(647, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(Heading)
                .addGap(1060, 1060, 1060))
        );

        jTabbedPane1.addTab("tab1", Home);

        Login.setPreferredSize(new java.awt.Dimension(730, 730));

        userPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Heading2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Heading2.setText("Login As A Worker");

        message.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel8.setText(" User ID:");

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel18.setText("password:");

        workerLogin.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        workerLogin.setText("Login");
        workerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Name: ");

        name.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        id.setToolTipText("");
        id.setName(""); // NOI18N

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addGap(36, 36, 36)))
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id)
                                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(password))))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(workerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addComponent(Heading2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Heading2)
                .addGap(18, 18, 18)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(workerLogin)
                .addGap(40, 40, 40))
        );

        id.getAccessibleContext().setAccessibleName("");

        userPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Heading3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Heading3.setText("Login As A User");

        message2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel9.setText(" User ID:");

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel20.setText("password:");

        userLogin.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        userLogin.setText("Login");
        userLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Name: ");

        name2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });

        id2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout userPanel1Layout = new javax.swing.GroupLayout(userPanel1);
        userPanel1.setLayout(userPanel1Layout);
        userPanel1Layout.setHorizontalGroup(
            userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanel1Layout.createSequentialGroup()
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(userPanel1Layout.createSequentialGroup()
                                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addGap(36, 36, 36)))
                                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id2)
                                    .addComponent(name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(password2))))
                    .addGroup(userPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanel1Layout.createSequentialGroup()
                        .addComponent(Heading3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanel1Layout.createSequentialGroup()
                        .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        userPanel1Layout.setVerticalGroup(
            userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Heading3)
                .addGap(18, 18, 18)
                .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(userLogin)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(userPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", Login);

        acdetailsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Heading4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Heading4.setText("Create User A/c");

        message3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setText("Name: ");

        name3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("A/c No.:");

        acNo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel19.setText("password:");

        password3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        createUserbutton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        createUserbutton.setText("Create User");
        createUserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserbuttonActionPerformed(evt);
            }
        });

        id4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        id4.setText("ID:");

        id3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        message4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 10)); // NOI18N

        javax.swing.GroupLayout acdetailsPanelLayout = new javax.swing.GroupLayout(acdetailsPanel);
        acdetailsPanel.setLayout(acdetailsPanelLayout);
        acdetailsPanelLayout.setHorizontalGroup(
            acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acdetailsPanelLayout.createSequentialGroup()
                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acdetailsPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(Heading4))
                    .addGroup(acdetailsPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(acdetailsPanelLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(createUserbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(acdetailsPanelLayout.createSequentialGroup()
                                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acdetailsPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(18, 18, 18))
                                        .addGroup(acdetailsPanelLayout.createSequentialGroup()
                                            .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(30, 30, 30)))
                                    .addGroup(acdetailsPanelLayout.createSequentialGroup()
                                        .addComponent(id4)
                                        .addGap(62, 62, 62)))
                                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(message4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(name3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(acNo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(id3)
                                        .addComponent(password3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acdetailsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        acdetailsPanelLayout.setVerticalGroup(
            acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acdetailsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Heading4)
                .addGap(18, 18, 18)
                .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(message4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(acdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(createUserbutton)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CreateUserLayout = new javax.swing.GroupLayout(CreateUser);
        CreateUser.setLayout(CreateUserLayout);
        CreateUserLayout.setHorizontalGroup(
            CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(acdetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        CreateUserLayout.setVerticalGroup(
            CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(acdetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", CreateUser);

        MainPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, -36, 1550, 1170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        message.setText("");
        message2.setText("");
        message3.setText("");
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_homeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        message.setText("");
        message2.setText("");
        message3.setText("");
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_loginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        message.setText("");
        message2.setText("");
        message3.setText("");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed

        message.setText("");
        message2.setText("");
        message3.setText("");
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_createUserActionPerformed

    private void workerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerLoginActionPerformed
        
        message.setText("");
        message2.setText("");
        message3.setText("");
        workerLogin();
    }//GEN-LAST:event_workerLoginActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void userLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginActionPerformed
        message.setText("");
        message2.setText("");
        message3.setText("");
        userLogin();
    }//GEN-LAST:event_userLoginActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void createUserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserbuttonActionPerformed
        message.setText("");
        message2.setText("");
        message3.setText("");
        createUser();
    }//GEN-LAST:event_createUserbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateUser;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading2;
    private javax.swing.JLabel Heading3;
    private javax.swing.JLabel Heading4;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField acNo;
    private javax.swing.JPanel acdetailsPanel;
    private javax.swing.JButton createUser;
    private javax.swing.JButton createUserbutton;
    private javax.swing.JButton exit;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField id3;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton login;
    private javax.swing.JLabel message;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JLabel message4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField password3;
    private javax.swing.JButton userLogin;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel userPanel1;
    private javax.swing.JButton workerLogin;
    // End of variables declaration//GEN-END:variables
}
